- name: Configure webservers
  hosts: all
  become: true
  tasks:
      - name: Install apache
        yum:
          name: httpd
          state: latest

      - name: enabled apache
        systemd:
          name: httpd
          state: started
          enabled: yes